
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE LPAREN MINUS NUMBER PLUS RPAREN TIMESexpression : expression PLUS term\n                  | expression MINUS termnumber : NUMBERexpression : termterm : term TIMES factor\n            | term DIVIDE factorterm : factorfactor : NUMBERfactor : LPAREN expression RPAREN'
    
_lr_action_items = {'NUMBER':([0,5,6,7,8,9,],[4,4,4,4,4,4,]),'LPAREN':([0,5,6,7,8,9,],[5,5,5,5,5,5,]),'$end':([1,2,3,4,11,12,13,14,15,],[0,-4,-7,-8,-1,-2,-5,-6,-9,]),'PLUS':([1,2,3,4,10,11,12,13,14,15,],[6,-4,-7,-8,6,-1,-2,-5,-6,-9,]),'MINUS':([1,2,3,4,10,11,12,13,14,15,],[7,-4,-7,-8,7,-1,-2,-5,-6,-9,]),'RPAREN':([2,3,4,10,11,12,13,14,15,],[-4,-7,-8,15,-1,-2,-5,-6,-9,]),'TIMES':([2,3,4,11,12,13,14,15,],[8,-7,-8,8,8,-5,-6,-9,]),'DIVIDE':([2,3,4,11,12,13,14,15,],[9,-7,-8,9,9,-5,-6,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,5,],[1,10,]),'term':([0,5,6,7,],[2,2,11,12,]),'factor':([0,5,6,7,8,9,],[3,3,3,3,13,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_binop','app.py',35),
  ('expression -> expression MINUS term','expression',3,'p_expression_binop','app.py',36),
  ('number -> NUMBER','number',1,'p_number','app.py',39),
  ('expression -> term','expression',1,'p_expression_term','app.py',42),
  ('term -> term TIMES factor','term',3,'p_term_binop','app.py',46),
  ('term -> term DIVIDE factor','term',3,'p_term_binop','app.py',47),
  ('term -> factor','term',1,'p_term_factor','app.py',51),
  ('factor -> NUMBER','factor',1,'p_factor_num','app.py',55),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','app.py',59),
]
